apiVersion: v1
kind: ConfigMap
metadata:
  name: piraeus-controller
  namespace: kube-system
data:
  INIT_DEBUG: "false"
  ETCD_ENDPOINTS: piraeus-etcd.kube-system.svc.cluster.local:2379
  LS_CONTROLLERS: piraeus-controller.kube-system.svc.cluster.local:3370
---
apiVersion: v1
kind: Service
metadata:
  name: piraeus-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
spec:
  type: ClusterIP
  ports:
  - port: 3370
    name: rest-api
    targetPort: 3370
  selector:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: piraeus-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
spec:
  serviceName: piraeus-controller
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-controller
    spec:
      serviceAccount: piraeus-controller
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      dnsPolicy: ClusterFirst
      initContainers:
      - name: init
        image: daocloud.io/piraeus/piraeus-init:v0.5.3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: piraeus-controller
        args:
        - initController
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
      containers:
      - name: controller
        image: daocloud.io/piraeus/piraeus-controller:1.4.2-ha
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        ports:
        - name: rest-api
          containerPort: 3370
          hostPort: 3370
        - name: plain
          containerPort: 3376
          hostPort: 3376
        - name: ssl
          containerPort: 3377
          hostPort: 3377
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        env:
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          httpGet:
            port: 3370
          periodSeconds: 2
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: init
          mountPath: /etc/linstor
          subPath: etc/linstor
        - name: log
          mountPath: /var/log/linstor-controller
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: init
        emptyDir: {}
      - name: log
        hostPath:
          path: /var/log/piraeus/linstor-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: piraeus-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: piraeus-controller
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: piraeus-controller
  namespace: kube-system
roleRef:
  apiGroup: ""
  kind: Role
  name: piraeus-controller
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: piraeus-controller
  namespace: kube-system
  apiGroup: ""
